# Generated by Django 5.2.7 on 2025-10-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituto', models.CharField(db_column='tituto', max_length=150)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=250)),
                ('imagen', models.CharField(blank=True, db_column='imagen', max_length=150, null=True)),
                ('estado', models.IntegerField(db_column='estado')),
                ('fecha_creacion', models.DateTimeField(db_column='fecha_creacion')),
                ('fecha_inicio', models.DateTimeField(db_column='fecha_inicio')),
                ('fecha_fin', models.DateTimeField(db_column='fecha_fin')),
            ],
            options={
                'db_table': 'capacitaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CapacitacionesColaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
            ],
            options={
                'db_table': 'capacitaciones_colaboradores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_leccion', models.CharField(db_column='tituloLeccion', max_length=150)),
                ('tipo_leccion', models.CharField(db_column='tipoLeccion', max_length=150)),
                ('url', models.CharField(db_column='URL', max_length=150)),
            ],
            options={
                'db_table': 'lecciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modulo', models.CharField(db_column='nombreModulo', max_length=150)),
            ],
            options={
                'db_table': 'modulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreguntasLecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(db_column='pregunta', max_length=150)),
                ('tipo_pregunta', models.CharField(db_column='tipoPregunta', max_length=150)),
                ('url_multimedia', models.CharField(db_column='urlMultimedia', max_length=150)),
            ],
            options={
                'db_table': 'preguntas_lecciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(db_column='valor', max_length=100)),
                ('es_correcto', models.IntegerField(db_column='esCorrecto')),
                ('url_imagen', models.CharField(blank=True, db_column='urlImagen', max_length=150, null=True)),
            ],
            options={
                'db_table': 'respuestas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RespuestasColaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'respuestas_colaboradores',
                'managed': False,
            },
        ),
    ]
