# Generated by Django 5.2.7 on 2025-11-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='progresoCapacitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(db_column='completada', default=False)),
                ('progreso', models.DecimalField(db_column='progreso', decimal_places=2, default=0.0, max_digits=5)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
                ('fecha_completado', models.DateTimeField(auto_now_add=True, db_column='fecha_completada')),
            ],
            options={
                'db_table': 'capacitaciones_colaboradores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='progresolecciones',
            fields=[
                ('id_progreso', models.AutoField(db_column='id_progreso', primary_key=True, serialize=False)),
                ('completada', models.BooleanField(db_column='completada', default=0)),
                ('progreso', models.DecimalField(db_column='progreso', decimal_places=2, default=0.0, max_digits=5)),
                ('fecha_completado', models.DateTimeField(auto_now_add=True, db_column='fecha_completado')),
            ],
            options={
                'db_table': 'progreso_colaboradores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='progresoModulo',
            fields=[
                ('id_progreso', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('completada', models.BooleanField(db_column='completada', default=0)),
                ('progreso', models.DecimalField(db_column='progreso', decimal_places=2, default=0.0, max_digits=5)),
                ('fecha_completado', models.DateTimeField(auto_now_add=True, db_column='fecha_completado')),
            ],
            options={
                'db_table': 'progreso_modulo',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CapacitacionesColaboradores',
        ),
    ]
