# Generated by Django 5.2.7 on 2025-12-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0002_progresocapacitaciones_progresolecciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador_id', models.IntegerField(db_column='colaborador_id')),
                ('capacitacion_id', models.IntegerField(db_column='capacitacion_id')),
                ('archivo_pdf', models.FileField(db_column='archivo_pdf', upload_to='certificados_generados/%Y/%m/%d/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, db_column='fecha_generacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
            ],
            options={
                'db_table': 'certificados_generados',
                'indexes': [models.Index(fields=['colaborador_id', 'capacitacion_id'], name='certificado_colabor_e449f2_idx'), models.Index(fields=['fecha_generacion'], name='certificado_fecha_g_212f8e_idx')],
                'unique_together': {('colaborador_id', 'capacitacion_id')},
            },
        ),
    ]
