# Generated by Django 5.2.7 on 2025-12-24 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analitica', '0002_delete_proyectosunidadnegocio'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=150)),
                ('activo', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'examenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorreoExamenEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_trabajador', models.CharField(max_length=150)),
                ('documento_trabajador', models.CharField(max_length=50)),
                ('correo_destino', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo_correo', models.TextField()),
                ('enviado_correctamente', models.BooleanField(default=False)),
                ('error_envio', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.cargo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analitica.epresa')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correos_enviados', to='usuarios.colaboradores')),
            ],
            options={
                'verbose_name': 'Correo de Exámenes Enviado',
                'verbose_name_plural': 'Correos de Exámenes Enviados',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='ExamenesCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatorio', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_por_empresa', to='usuarios.cargo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_por_cargo', to='analitica.epresa')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='examenes.examen')),
            ],
            options={
                'verbose_name': 'Examen por Empresa y Cargo',
                'verbose_name_plural': 'Exámenes por Empresa y Cargo',
                'unique_together': {('empresa', 'cargo', 'examen')},
            },
        ),
    ]
