# Generated by Django 5.2.7 on 2025-12-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoexamenenviado',
            name='uuid_correo',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
