# Generated by Django 5.2.7 on 2026-01-02 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0004_alter_progresoagregado_unique_together_and_more'),
        ('examenes', '0002_add_uuid_correo'),
        ('usuarios', '0004_alter_usuarios_is_staff'),
    ]

    operations = [
        # Agregar nuevos campos a CorreoExamenEnviado
        migrations.AddField(
            model_name='correoexamenenviado',
            name='uuid_lote',
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text='Identificador único del lote de envío',
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name='correoexamenenviado',
            name='correos_destino',
            field=models.CharField(
                default='practicante.desarrollogh@regency.com.co,practicante.desarrollogh@regency.com.co',
                help_text='Emails separados por coma donde se envía el lote',
                max_length=500,
            ),
        ),
        # Crear la nueva tabla RegistroExamenes
        migrations.CreateModel(
            name='RegistroExamenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_trabajador', models.CharField(max_length=150)),
                ('documento_trabajador', models.CharField(db_index=True, max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_examenes', to='usuarios.cargo')),
                ('correo_lote', models.ForeignKey(help_text='Correo/lote al que pertenece este registro', on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to='examenes.correoexamenenviado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_examenes', to='analitica.epresa')),
            ],
            options={
                'verbose_name': 'Registro de Exámenes',
                'verbose_name_plural': 'Registros de Exámenes',
                'ordering': ['-fecha_registro'],
            },
        ),
        # Agregar unique_together a RegistroExamenes
        migrations.AddConstraint(
            model_name='registroexamenes',
            constraint=models.UniqueConstraint(
                fields=('correo_lote', 'documento_trabajador'),
                name='unique_correo_lote_documento'
            ),
        ),
    ]
