# Generated by Django 5.2.7 on 2026-01-02 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0004_alter_progresoagregado_unique_together_and_more'),
        ('examenes', '0002_add_uuid_correo'),
        ('usuarios', '0004_alter_usuarios_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correoexamenenviado',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Envío Masivo de Exámenes', 'verbose_name_plural': 'Envíos Masivos de Exámenes'},
        ),
        migrations.RemoveField(
            model_name='correoexamenenviado',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='correoexamenenviado',
            name='correo_destino',
        ),
        migrations.RemoveField(
            model_name='correoexamenenviado',
            name='documento_trabajador',
        ),
        migrations.RemoveField(
            model_name='correoexamenenviado',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='correoexamenenviado',
            name='nombre_trabajador',
        ),
        migrations.RemoveField(
            model_name='examenescargo',
            name='obligatorio',
        ),
        migrations.AlterField(
            model_name='correoexamenenviado',
            name='asunto',
            field=models.CharField(help_text='Asunto del correo', max_length=200),
        ),
        migrations.AlterField(
            model_name='correoexamenenviado',
            name='cuerpo_correo',
            field=models.TextField(help_text='Cuerpo del correo (tabla HTML)'),
        ),
        migrations.AlterField(
            model_name='correoexamenenviado',
            name='enviado_por',
            field=models.ForeignKey(help_text='Usuario que generó el envío', on_delete=django.db.models.deletion.PROTECT, related_name='correos_enviados', to='usuarios.colaboradores'),
        ),
    ]
