# Generated by Django 5.2.7 on 2026-01-04 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0005_registroexamenes_estado_trabajador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('examen', models.ForeignKey(help_text='Examen asignado', on_delete=django.db.models.deletion.CASCADE, related_name='trabajadores', to='examenes.examen')),
                ('registro_examen', models.ForeignKey(help_text='Registro de exámenes del trabajador', on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='examenes.registroexamenes')),
            ],
            options={
                'verbose_name': 'Examen Asignado a Trabajador',
                'verbose_name_plural': 'Exámenes Asignados a Trabajadores',
                'ordering': ['examen__nombre'],
                'unique_together': {('registro_examen', 'examen')},
            },
        ),
    ]
