# Generated by Django 5.2.7 on 2026-01-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0004_alter_progresoagregado_unique_together_and_more'),
        ('examenes', '0006_examentrabajador_and_more'),
        ('usuarios', '0004_alter_usuarios_is_staff'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registroexamenes',
            name='unique_correo_lote_documento',
        ),
        migrations.AlterUniqueTogether(
            name='examenescargo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='correoexamenenviado',
            name='uuid_lote',
        ),
        migrations.AddField(
            model_name='correoexamenenviado',
            name='tipo_examen',
            field=models.CharField(choices=[('INGRESO', 'Examen de Ingreso'), ('PERIODICO', 'Examen Periódico')], db_index=True, default='INGRESO', help_text='Tipo de examen: INGRESO o PERIODICO', max_length=20),
        ),
        migrations.AddField(
            model_name='correoexamenenviado',
            name='uuid_correo',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Identificador único del lote de envío', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='examenescargo',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Examen de Ingreso'), ('PERIODICO', 'Examen Periódico')], db_index=True, default='INGRESO', help_text='Tipo de examen: INGRESO o PERIODICO', max_length=20),
        ),
        migrations.AddField(
            model_name='registroexamenes',
            name='examenes_asignados',
            field=models.TextField(blank=True, help_text='Lista de exámenes separados por coma', null=True),
        ),
        migrations.AddField(
            model_name='registroexamenes',
            name='tipo_examen',
            field=models.CharField(choices=[('INGRESO', 'Examen de Ingreso'), ('PERIODICO', 'Examen Periódico')], db_index=True, default='INGRESO', help_text='Tipo de examen: INGRESO o PERIODICO', max_length=20),
        ),
        migrations.AddField(
            model_name='registroexamenes',
            name='uuid_trabajador',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Identificador único del trabajador para este examen', max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='examenescargo',
            unique_together={('empresa', 'cargo', 'examen', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='registroexamenes',
            unique_together={('correo_lote', 'documento_trabajador')},
        ),
    ]
