# Generated by Django 5.2.7 on 2026-01-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0007_add_tipo_to_examenescargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroexamenes',
            name='examenes_realizados',
            field=models.JSONField(blank=True, default=dict, help_text='JSON con {id_examen: {completado: bool, fecha: datetime, resultado: str}}', null=True),
        ),
        migrations.AlterField(
            model_name='correoexamenenviado',
            name='tipo_examen',
            field=models.CharField(choices=[('INGRESO', 'Examen de Ingreso'), ('PERIODICO', 'Examen Periódico'), ('RETIRO', 'Examen de Retiro'), ('ESPECIAL', 'Examen Especial'), ('POST_INCAPACIDAD', 'Examen Post-Incapacidad')], db_index=True, default='INGRESO', help_text='Tipo de examen: INGRESO, PERIODICO, RETIRO, ESPECIAL o POST_INCAPACIDAD', max_length=20),
        ),
        migrations.AlterField(
            model_name='examenescargo',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Examen de Ingreso'), ('PERIODICO', 'Examen Periódico'), ('RETIRO', 'Examen de Retiro'), ('ESPECIAL', 'Examen Especial'), ('POST_INCAPACIDAD', 'Examen Post-Incapacidad')], db_index=True, default='INGRESO', help_text='Tipo de examen: INGRESO, PERIODICO, RETIRO, ESPECIAL o POST_INCAPACIDAD', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroexamenes',
            name='tipo_examen',
            field=models.CharField(choices=[('INGRESO', 'Examen de Ingreso'), ('PERIODICO', 'Examen Periódico'), ('RETIRO', 'Examen de Retiro'), ('ESPECIAL', 'Examen Especial'), ('POST_INCAPACIDAD', 'Examen Post-Incapacidad')], db_index=True, help_text='Tipo de examen: INGRESO, PERIODICO, RETIRO, ESPECIAL o POST_INCAPACIDAD', max_length=20),
        ),
    ]
