# Generated by Django 5.2.7 on 2026-01-05 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0008_registroexamenes_examenes_realizados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correoexamenenviado',
            name='tipo_examen',
            field=models.CharField(choices=[('INGRESO', 'Examen de Ingreso'), ('PERIODICO', 'Examen Periódico'), ('RETIRO', 'Examen de Retiro'), ('ESPECIAL', 'Examen Especial'), ('POST_INCAPACIDAD', 'Examen Post-Incapacidad'), ('MIXTO', 'Múltiples tipos')], db_index=True, default='INGRESO', help_text='Tipo de examen: INGRESO, PERIODICO, RETIRO, ESPECIAL, POST_INCAPACIDAD o MIXTO', max_length=20),
        ),
        migrations.CreateModel(
            name='RegistroExamenesEnviados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(choices=[('INGRESO', 'Examen de Ingreso'), ('PERIODICO', 'Examen Periódico'), ('RETIRO', 'Examen de Retiro'), ('ESPECIAL', 'Examen Especial'), ('POST_INCAPACIDAD', 'Examen Post-Incapacidad')], db_index=True, help_text='Tipo de examen asignado', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('no_realizado', 'No Realizado')], db_index=True, default='pendiente', help_text='Estado del examen', max_length=20)),
                ('resultado', models.CharField(blank=True, choices=[('aprobado', 'Aprobado'), ('no_aprobado', 'No Aprobado'), ('', 'Sin resultado')], help_text='Resultado del examen', max_length=50, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('examen', models.ForeignKey(db_constraint=False, help_text='Examen asignado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='registros_enviados', to='examenes.examen')),
                ('registro_examen', models.ForeignKey(help_text='Registro del trabajador', on_delete=django.db.models.deletion.CASCADE, related_name='examenes_enviados', to='examenes.registroexamenes')),
            ],
            options={
                'verbose_name': 'Registro de Examen Enviado',
                'verbose_name_plural': 'Registros de Exámenes Enviados',
                'ordering': ['-fecha_envio'],
                'unique_together': {('registro_examen', 'examen', 'tipo_examen')},
            },
        ),
    ]
