# Generated by Django 5.2.7 on 2026-01-15 20:10

from django.db import migrations, models

def _drop_examenes_realizados(apps, schema_editor):
    """Drop `examenes_realizados` column if it exists (works across MySQL versions)."""
    conn = schema_editor.connection
    table_name = 'examenes_registroexamenes'
    col_name = 'examenes_realizados'
    with conn.cursor() as cursor:
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.COLUMNS "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = %s",
            (table_name, col_name)
        )
        exists = cursor.fetchone()[0]
        if exists:
            cursor.execute(f"ALTER TABLE `{table_name}` DROP COLUMN `{col_name}`")


def _add_ciudad_if_missing(apps, schema_editor):
    """Add `ciudad` column only if it doesn't exist."""
    conn = schema_editor.connection
    table_name = 'examenes_registroexamenes'
    col_name = 'ciudad'
    with conn.cursor() as cursor:
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.COLUMNS "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = %s",
            (table_name, col_name)
        )
        exists = cursor.fetchone()[0]
        if not exists:
            cursor.execute(f"ALTER TABLE `{table_name}` ADD COLUMN `{col_name}` varchar(100) NULL")


def _drop_registro_enviados_table_if_exists(apps, schema_editor):
    """Drop `examenes_registroexamenesenviados` table if it exists."""
    conn = schema_editor.connection
    table_name = 'examenes_registroexamenesenviados'
    with conn.cursor() as cursor:
        cursor.execute(
            "SELECT COUNT(*) FROM information_schema.TABLES "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s",
            (table_name,)
        )
        exists = cursor.fetchone()[0]
        if exists:
            cursor.execute(f"DROP TABLE `{table_name}`")


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0009_remove_registroexamenes_examenes_realizados_and_more'),
    ]

    operations = [
        migrations.RunPython(_drop_examenes_realizados, migrations.RunPython.noop),
        migrations.RunPython(_add_ciudad_if_missing, migrations.RunPython.noop),
        migrations.RunPython(_drop_registro_enviados_table_if_exists, migrations.RunPython.noop),
    ]
