# Generated by Django 5.2.7 on 2026-04-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0011_add_alturas_exam_type'),
        ('examenes', '0012_add_alturas_exam_type'),
    ]

    operations = [
    ]
