# Generated by Django 5.2.7 on 2026-08-03 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0013_merge_20260407_1555'),
        ('usuarios', '0004_alter_usuarios_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadoRegistroExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(help_text='Colaborador que realizó el cambio de estado a Completado', on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado_examenes', to='usuarios.colaboradores')),
                ('registro_examen', models.ForeignKey(help_text='Registro de examen del trabajador que cambió de estado', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='examenes.registroexamenes')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Registro de Examen',
                'verbose_name_plural': 'Historial de Estados de Registros de Exámenes',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
