# Generated by Django 5.2.7 on 2025-10-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centroop',
            fields=[
                ('id_centrop', models.AutoField(db_column='idCentrOp', primary_key=True, serialize=False)),
                ('nombre_centrop', models.CharField(db_column='nombreCentrOp', max_length=30)),
                ('estado_centrop', models.IntegerField(db_column='estadoCentrOp', default=1)),
            ],
            options={
                'db_table': 'centroop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Epresa',
            fields=[
                ('id_empresa', models.AutoField(db_column='Idempresa', primary_key=True, serialize=False)),
                ('nit_empresa', models.CharField(db_column='nitempresa', max_length=20)),
                ('nombre_empresa', models.CharField(db_column='nombre_empresa', max_length=20)),
                ('estado_empresa', models.IntegerField(db_column='estadoempresa', default=1)),
            ],
            options={
                'db_table': 'epresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(db_column='Idproyecto', primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(db_column='nombreProyecto', max_length=50)),
                ('estado_proyecto', models.IntegerField(db_column='estadoProyecto', default=1)),
            ],
            options={
                'db_table': 'proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyectosUnidadnegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'proyectos_unidadnegocio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidadnegocio',
            fields=[
                ('id_unidad', models.AutoField(db_column='idunidad', primary_key=True, serialize=False)),
                ('nombre_unidad', models.CharField(db_column='nombreunidad', max_length=30)),
                ('descripcion_unidad', models.CharField(db_column='descripcionUnidad', max_length=100)),
                ('estado_unidad', models.IntegerField(db_column='estadoUnidad', default=1)),
            ],
            options={
                'db_table': 'unidadnegocio',
                'managed': False,
            },
        ),
    ]
