# Generated by Django 5.2.7 on 2025-12-29 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0002_delete_proyectosunidadnegocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoAgregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_total', models.DecimalField(db_column='promedio', decimal_places=2, default=0.0, max_digits=5)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('centro', models.ForeignKey(blank=True, db_column='id_centro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='analitica.centroop')),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='analitica.epresa')),
                ('proyecto', models.ForeignKey(blank=True, db_column='id_proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='analitica.proyecto')),
                ('unidad', models.ForeignKey(blank=True, db_column='id_unidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='analitica.unidadnegocio')),
            ],
            options={
                'db_table': 'progreso_agregado',
                'managed': True,
                'indexes': [models.Index(fields=['empresa'], name='progreso_ag_id_empr_069a8e_idx'), models.Index(fields=['unidad'], name='progreso_ag_id_unid_d3bb29_idx'), models.Index(fields=['proyecto'], name='progreso_ag_id_proy_c53c19_idx'), models.Index(fields=['centro'], name='progreso_ag_id_cent_5ba143_idx'), models.Index(fields=['fecha_actualizacion'], name='progreso_ag_fecha_a_66799b_idx')],
                'unique_together': {('empresa', 'unidad', 'proyecto', 'centro')},
            },
        ),
    ]
