# Generated by Django 5.2.7 on 2025-12-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0003_progresoagregado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progresoagregado',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='progresoagregado',
            name='anio',
            field=models.IntegerField(blank=True, db_column='anio', null=True),
        ),
        migrations.AddField(
            model_name='progresoagregado',
            name='mes',
            field=models.IntegerField(blank=True, db_column='mes', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='progresoagregado',
            unique_together={('empresa', 'unidad', 'proyecto', 'centro', 'mes', 'anio')},
        ),
        migrations.AddIndex(
            model_name='progresoagregado',
            index=models.Index(fields=['mes', 'anio'], name='progreso_ag_mes_6379fa_idx'),
        ),
    ]
