# Generated by Django 5.2.7 on 2025-10-22 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, db_column='usuario', max_length=30, null=True, unique=True)),
                ('clave', models.CharField(db_column='clave', max_length=500)),
                ('is_active', models.BooleanField(db_column='estadoUsuario', default=True)),
                ('is_staff', models.BooleanField(db_column='tipousuario', default=False)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idcargo', models.AutoField(db_column='idCargo', primary_key=True, serialize=False)),
                ('nombrecargo', models.CharField(db_column='nombreCargo', max_length=30)),
                ('estadocargo', models.IntegerField(db_column='estadoCargo', default=1)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id_colaborador', models.AutoField(db_column='idColaborador', primary_key=True, serialize=False)),
                ('cc_colaborador', models.CharField(blank=True, db_column='ccColaborador', max_length=30, unique=True)),
                ('nombre_colaborador', models.CharField(db_column='nombreColaborador', max_length=30)),
                ('apellido_colaborador', models.CharField(db_column='apellidoColaborador', max_length=30)),
                ('correo_colaborador', models.CharField(blank=True, db_column='correoColaborador', max_length=50, null=True)),
                ('telefo_colaborador', models.CharField(blank=True, db_column='telefoColaborador', max_length=20, null=True)),
                ('estado_colaborador', models.IntegerField(db_column='estadoColaborador', default=1)),
            ],
            options={
                'db_table': 'colaboradores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Niveles',
            fields=[
                ('id_nivel', models.AutoField(db_column='idnivel', primary_key=True, serialize=False)),
                ('nombre_nivel', models.CharField(db_column='nombrenivel', max_length=50)),
                ('estado_nivel', models.IntegerField(db_column='estadonivel', default=1)),
                ('prom', models.CharField(blank=True, db_column='prom', max_length=50, null=True)),
            ],
            options={
                'db_table': 'niveles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id_regional', models.AutoField(db_column='idregional', primary_key=True, serialize=False)),
                ('nombre_regional', models.CharField(db_column='nombreregional', max_length=30)),
                ('estado_regional', models.IntegerField(db_column='estadoRegional', default=1)),
            ],
            options={
                'db_table': 'regional',
                'managed': False,
            },
        ),
    ]
