# Generated by Django 5.2.7 on 2026-02-20 19:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_alter_usuarios_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdicionMundial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('activa', models.BooleanField(default=False)),
                ('bloqueo_configuracion', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Edición del Mundial',
                'verbose_name_plural': 'Ediciones del Mundial',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('bandera_imagen', models.ImageField(blank=True, null=True, upload_to='banderas/')),
                ('bandera_emoji', models.CharField(blank=True, max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_resultado_exacto', models.IntegerField(default=3)),
                ('puntos_ganador_correcto', models.IntegerField(default=1)),
                ('multiplicador_grupos', models.CharField(default='x1', max_length=5)),
                ('multiplicador_dieciseisavos', models.CharField(default='x1.25', max_length=5)),
                ('multiplicador_octavos', models.CharField(default='x1.5', max_length=5)),
                ('multiplicador_cuartos', models.CharField(default='x1.75', max_length=5)),
                ('multiplicador_semifinales', models.CharField(default='x2', max_length=5)),
                ('multiplicador_tercer_puesto', models.CharField(default='x2.5', max_length=5)),
                ('multiplicador_final', models.CharField(default='x3', max_length=5)),
                ('puntos_campeon', models.IntegerField(default=50)),
                ('puntos_subcampeon', models.IntegerField(default=30)),
                ('puntos_tercer_lugar', models.IntegerField(default=20)),
                ('puntos_maximo_goleador', models.IntegerField(default=25)),
                ('porcentaje_primer_lugar', models.CharField(default='50%', max_length=10)),
                ('porcentaje_segundo_lugar', models.CharField(default='30%', max_length=10)),
                ('porcentaje_tercer_lugar', models.CharField(default='20%', max_length=10)),
                ('fondo_premios_total', models.CharField(default='$50,000', max_length=50)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('edicion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='mundial.edicionmundial')),
            ],
            options={
                'verbose_name': 'Configuración del Torneo',
                'verbose_name_plural': 'Configuraciones del Torneo',
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('fase', models.CharField(choices=[('Grupos', 'Grupos'), ('16avos', '16avos'), ('Octavos', 'Octavos'), ('Cuartos', 'Cuartos'), ('Semifinales', 'Semifinales'), ('Tercer Puesto', 'Tercer Puesto'), ('Final', 'Final')], max_length=20)),
                ('grupo', models.CharField(blank=True, max_length=1, null=True)),
                ('multiplicador', models.CharField(default='x1', max_length=5)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('bloqueado', 'Bloqueado'), ('finalizado', 'Finalizado')], default='abierto', max_length=20)),
                ('goles_local', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('goles_visitante', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fue_a_penaltis', models.BooleanField(default=False)),
                ('penaltis_local', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('penaltis_visitante', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('edicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='mundial.edicionmundial')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_local', to='mundial.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_visitante', to='mundial.equipo')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('goles_visitante', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ganador', models.CharField(choices=[('local', 'Local'), ('visitante', 'Visitante'), ('empate', 'Empate')], max_length=10)),
                ('predice_penaltis', models.BooleanField(default=False)),
                ('penaltis_local', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('penaltis_visitante', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('ganador_penaltis', models.CharField(blank=True, choices=[('local', 'Local'), ('visitante', 'Visitante')], max_length=10, null=True)),
                ('puntos_obtenidos', models.IntegerField(blank=True, null=True)),
                ('puntos_penaltis', models.IntegerField(blank=True, null=True)),
                ('es_acierto_exacto', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones_mundial', to='usuarios.colaboradores')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='mundial.partido')),
            ],
            options={
                'verbose_name': 'Predicción',
                'verbose_name_plural': 'Predicciones',
            },
        ),
        migrations.CreateModel(
            name='PrediccionEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('campeon', 'Campeón'), ('subcampeon', 'Subcampeón'), ('tercer_lugar', 'Tercer Lugar'), ('maximo_goleador', 'Máximo Goleador')], max_length=20)),
                ('jugador_seleccionado', models.CharField(blank=True, max_length=200, null=True)),
                ('puntos_obtenidos', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones_especiales_mundial', to='usuarios.colaboradores')),
                ('equipo_seleccionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicciones_especiales', to='mundial.equipo')),
            ],
            options={
                'verbose_name': 'Predicción Especial',
                'verbose_name_plural': 'Predicciones Especiales',
            },
        ),
        migrations.CreateModel(
            name='RankingMundial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField(default=0)),
                ('puntos_partidos', models.IntegerField(default=0)),
                ('aciertos_exactos', models.IntegerField(default=0)),
                ('puntos_especiales', models.IntegerField(default=0)),
                ('predicciones_especiales_acertadas', models.IntegerField(default=0)),
                ('puntos_totales', models.IntegerField(default=0)),
                ('tendencia', models.IntegerField(default=0)),
                ('fecha_primera_prediccion', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings_mundial', to='usuarios.colaboradores')),
                ('edicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='mundial.edicionmundial')),
            ],
            options={
                'verbose_name': 'Ranking Mundial',
                'verbose_name_plural': 'Rankings Mundiales',
                'ordering': ['posicion', 'fecha_primera_prediccion'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionPrediccionEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('campeon', 'Campeón'), ('subcampeon', 'Subcampeón'), ('tercer_lugar', 'Tercer Lugar'), ('maximo_goleador', 'Máximo Goleador')], max_length=30)),
                ('habilitada', models.BooleanField(default=True)),
                ('fecha_cierre', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('resuelta', 'Resuelta')], default='abierta', max_length=20)),
                ('puntos_acierto', models.IntegerField(default=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('edicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs_predicciones_especiales', to='mundial.edicionmundial')),
            ],
            options={
                'verbose_name': 'Configuración de Predicción Especial',
                'verbose_name_plural': 'Configuraciones de Predicciones Especiales',
                'ordering': ['fecha_cierre'],
                'unique_together': {('edicion', 'tipo')},
            },
        ),
        migrations.AddIndex(
            model_name='partido',
            index=models.Index(fields=['fecha', 'hora'], name='mundial_par_fecha_06a903_idx'),
        ),
        migrations.AddIndex(
            model_name='partido',
            index=models.Index(fields=['fase', 'estado'], name='mundial_par_fase_f0ee1a_idx'),
        ),
        migrations.AddIndex(
            model_name='partido',
            index=models.Index(fields=['estado'], name='mundial_par_estado_6c536d_idx'),
        ),
        migrations.AddIndex(
            model_name='partido',
            index=models.Index(fields=['edicion', 'estado'], name='mundial_par_edicion_20c174_idx'),
        ),
        migrations.AddIndex(
            model_name='prediccion',
            index=models.Index(fields=['colaborador', 'partido'], name='mundial_pre_colabor_531eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='prediccion',
            index=models.Index(fields=['partido'], name='mundial_pre_partido_a5939c_idx'),
        ),
        migrations.AddIndex(
            model_name='prediccion',
            index=models.Index(fields=['colaborador', 'creado_en'], name='mundial_pre_colabor_39a3e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prediccion',
            unique_together={('colaborador', 'partido')},
        ),
        migrations.AddIndex(
            model_name='prediccionespecial',
            index=models.Index(fields=['colaborador', 'tipo'], name='mundial_pre_colabor_0fc5ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prediccionespecial',
            unique_together={('colaborador', 'tipo')},
        ),
        migrations.AddIndex(
            model_name='rankingmundial',
            index=models.Index(fields=['edicion', 'puntos_totales'], name='mundial_ran_edicion_5ec39d_idx'),
        ),
        migrations.AddIndex(
            model_name='rankingmundial',
            index=models.Index(fields=['edicion', 'posicion'], name='mundial_ran_edicion_50575d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rankingmundial',
            unique_together={('edicion', 'colaborador')},
        ),
    ]
