# Generated by Django 5.2.7 on 2026-03-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0003_update_equipo_bandera_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuraciontorneo',
            name='puntos_campeon',
        ),
        migrations.RemoveField(
            model_name='configuraciontorneo',
            name='puntos_maximo_goleador',
        ),
        migrations.RemoveField(
            model_name='configuraciontorneo',
            name='puntos_subcampeon',
        ),
        migrations.RemoveField(
            model_name='configuraciontorneo',
            name='puntos_tercer_lugar',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='bandera_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mundial/banderas/'),
        ),
    ]
