# Generated by Django 5.2.7 on 2026-03-16 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0004_remove_configuraciontorneo_puntos_campeon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionprediccionespecial',
            name='resultado_equipo',
            field=models.ForeignKey(blank=True, help_text='Equipo ganador real (para campeón, subcampeón, tercer lugar)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_especiales', to='mundial.equipo'),
        ),
        migrations.AddField(
            model_name='configuracionprediccionespecial',
            name='resultado_jugador',
            field=models.CharField(blank=True, help_text='Jugador ganador real (para máximo goleador)', max_length=200, null=True),
        ),
    ]
