# Generated by Django 5.2.7 on 2026-03-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0005_configuracionprediccionespecial_resultado_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionprediccionespecial',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('bloqueada', 'Bloqueada'), ('resuelta', 'Resuelta')], default='abierta', max_length=20),
        ),
    ]
