# Generated by Django 5.2.7 on 2026-03-17 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0006_alter_configuracionprediccionespecial_estado'),
        ('usuarios', '0004_alter_usuarios_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankingmundial',
            name='predicciones_especiales_acertadas',
        ),
        migrations.RemoveField(
            model_name='rankingmundial',
            name='puntos_especiales',
        ),
        migrations.CreateModel(
            name='RankingEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField(default=0)),
                ('puntos_especiales', models.IntegerField(default=0)),
                ('predicciones_especiales_acertadas', models.IntegerField(default=0)),
                ('puntos_totales', models.IntegerField(default=0)),
                ('tendencia', models.IntegerField(default=0)),
                ('fecha_primera_prediccion', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings_especiales', to='usuarios.colaboradores')),
                ('edicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_especial', to='mundial.edicionmundial')),
            ],
            options={
                'verbose_name': 'Ranking Especial',
                'verbose_name_plural': 'Rankings Especiales',
                'ordering': ['posicion', 'fecha_primera_prediccion'],
                'indexes': [models.Index(fields=['edicion', 'puntos_totales'], name='mundial_ran_edicion_f4e56b_idx'), models.Index(fields=['edicion', 'posicion'], name='mundial_ran_edicion_335d66_idx')],
                'unique_together': {('edicion', 'colaborador')},
            },
        ),
    ]
