# Generated by Django 5.2.7 on 2026-03-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0007_remove_rankingmundial_predicciones_especiales_acertadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='bandera_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
