# Generated by Django 5.2.7 on 2026-03-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0008_add_bandera_url_to_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='edicion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
