# Generated by Django 5.2.7 on 2026-03-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0009_add_codigo_edicion_to_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='edicion',
        ),
    ]
